<?xml version="1.0" encoding="utf-8"?>
<Database Name="Music" Class="MusicDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Music;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MusicConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.albums" Member="albums">
    <Type Name="album">
      <Column Name="album_id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="album_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="album_artist" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="album_price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>